# Generated by Django 3.2.9 on 2021-11-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('cantidad_perfiles', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_usuario',
            fields=[
                ('id_usuario', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_gato', models.CharField(max_length=50)),
                ('sexo_gato', models.CharField(max_length=9)),
                ('raza_gato', models.CharField(max_length=30)),
                ('edad_gato', models.PositiveIntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_advertidos_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_reportado', models.PositiveIntegerField()),
                ('fecha_advertencia', models.DateField()),
                ('razon_reporte', models.TextField()),
                ('razon_advertencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_baneados_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_baneado', models.PositiveIntegerField()),
                ('id_cliente_acusante', models.PositiveIntegerField()),
                ('razon_reporte', models.TextField()),
                ('razon_baneado', models.TextField()),
                ('fecha_baneo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_reportados_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_reportado', models.PositiveIntegerField()),
                ('id_cliente_acusante', models.PositiveIntegerField()),
                ('fecha_reporte', models.DateField()),
                ('razon_reporte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_reportados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_reportado', models.PositiveIntegerField()),
                ('fecha_reporte', models.DateField()),
                ('razon_reporte', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.perfil_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_reportado', models.PositiveIntegerField()),
                ('fecha_like', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.perfil_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_interes', models.PositiveIntegerField()),
                ('fecha_like', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.perfil_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sueldo', models.PositiveSmallIntegerField()),
                ('anterior_cargo', models.CharField(max_length=50)),
                ('fecha_inicio_trabajo', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('sede_trabajo', models.CharField(max_length=50)),
                ('fecha_fin_trabajo', models.DateField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('id_moderador', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sede_encargada', models.CharField(max_length=50)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mensaje', models.DateField()),
                ('mensaje', models.TextField()),
                ('reaccion', models.CharField(max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.perfil_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('area_encargada', models.CharField(max_length=30)),
                ('superior_inmediato', models.PositiveIntegerField()),
                ('id_gerente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_designada', models.CharField(max_length=50)),
                ('jefe_inmediato', models.PositiveIntegerField()),
                ('rol', models.CharField(max_length=50)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tincat.persona'),
        ),
    ]
